### ISSUE TITLE
BUG:Wrong link to the post edit page

### ISSUE THREAD

**Issue by mediavinc** [MediakodTeam/wp-plugin-deployeur#5]
**Steps to reproduce:**

1. Edit a page or post and save
2. Naviguate to /wp-admin/admin.php?page=deployeur to see the list of pending edits
3. Check the link behind the post title's content displayed under the item : Username updated post "post title"

(the plugin is used with the Faust.js starter of wpengine)

**Actual result:**

the link is wrong and look like this https://mywebsite.be/wp-admin/'https://mywebsite.be/wp-admin/post.php?post=19759&action=edit'

**Expected result:**

a correct link direct to the post edit screen https://mywebsite.be/wp-admin/post.php?post=19759&action=edit

**Comment by MKlblangenois** [comment]
Closed with https://github.com/MediakodTeam/wp-plugin-deployeur/commit/95405d24315ff7010d849433a04d0fc03786213c
